stages:
    - build

build:
    stage: build
    # rules:
    #   - changes:
    #     - src/*
    script:
        - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$SSH_PRIVATE_KEY")
        - mkdir -p ~/.ssh
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - ssh root@$server "cd /home/alious/digi-nashr; git reset --hard;"
        - ssh root@$server "cd /home/alious/digi-nashr; git pull;"
        - ssh root@$server "cd /home/alious/digi-nashr; npm ci;"
        - ssh root@$server "cd /home/alious/digi-nashr; npm run build;"
        - ssh root@$server "cd /home/alious/digi-nashr; pm2 restart diginashr.front"
