import Head from 'next/head'
import HeaderOnly from 'layouts/header-only.js'
import styles from 'styles/pages/Home.module.scss'
import CarouselContainer from "components/common/carousel/carouselContainer";
import Accordion from "components/common/accordion";
import axios from 'axios';
import { Endpoints } from 'utils/endpoints'
import { useEffect, useState } from 'react'
export default function Home({ pageInfo }) {

    console.log('pageInfo', pageInfo)
    const [sections, setSections] = useState()
    useEffect(() => {
        let sectionsTmp = [];
        pageInfo.sections.map((sec) => {
            let optTemp = [];
            sec.posts.map((post) => {
                optTemp.push({
                    title: post.title,
                    subTitle: post.description,
                    image: post.coverImage?.url,
                    route: '/post/' + post._id,
                    bestSeller: post.bestSeller ? true : false,
                    contentType: post.contentType
                })
            })
            let tmp = {
                title: sec.title,
                options: optTemp,
                slidesPerView: (sec.contentType == 'magazine' || sec.contentType == 'article') ? 6 : 4,
                radius: true,
                page: '/post/' + sec._id,
                type: sec.contentType || 'best',
            }
            sectionsTmp.push(tmp);

        })
        setSections([...sectionsTmp])
    }, [])

    console.log('sec', sections)

    return (
        <div>
            <Head>
                <title>دیجی نشر</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='container'>

                {sections?.map((carousel) => (
                    <CarouselContainer
                        key={carousel.title}
                        title={carousel.title}
                        carouselOptions={
                            {
                                items: carousel.options,
                                swiperOptions: { slidesPerView: carousel.slidesPerView },
                                radius: carousel.radius,
                                type: carousel.type,
                                // image: carousel.image,
                                page: carousel.page,
                            }
                        }
                    />
                ))}

                <div className={styles.accordionContainer}>
                    <Accordion />
                </div>
            </div>
        </div>
    )
}

export async function getServerSideProps(context) {

    const pageInfo = await axios.get(`${Endpoints.baseUrl}/pages/home`)

    return {
        props: {
            pageInfo: pageInfo.data.data.page
        }, // will be passed to the page component as props

    };

}